SELECT * FROM Household;
SELECT * FROM User_information;
SELECT * FROM Household_user;
SELECT * FROM Account;
SELECT * FROM Transactions;
SELECT * FROM Daily_balance;
SELECT * FROM Privileges;
SELECT * FROM User_privilege;
SELECT * FROM User_account;
